spring:
  application:
    name: blog-api
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN


aws:
  region: ${AWS_DEFAULT_REGION}
  services:
    dynamodb:
      uri: ${DYNAMO_DB_URI}
      key: ${DYNAMO_DB_KEY}
      secret: ${DYNAMO_DB_SECRET}
      blogTable: ${DYNAMO_DB_TABLE_BLOG:blog_posts}
    s3:
      upload:
        baseLocation: ${S3_LOCATION} #blog-posts.csv
management:
  endpoints:
    web:
      exposure:
        include: info,health
    enabled-by-default: true

logging:
  level:
    org:
      springframework:
        security: DEBUG